# Generated by Django 3.2.16 on 2023-01-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_ticket_for_self'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='for_self',
            field=models.BooleanField(default=False),
        ),
    ]
