# Generated by Django 3.2.16 on 2023-01-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20230119_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fave_team',
            field=models.CharField(choices=[('red_bull', 'Red Bull'), ('ferrari', 'Ferrari'), ('mercedes', 'Mercedes'), ('alpine', 'Alpine'), ('mclaren', 'McLaren'), ('alfa_romeo', 'Alfa Romeo'), ('aston_martin', 'Aston Martin'), ('haas', 'Haas'), ('alphatauri', 'AlphaTauri'), ('williams', 'Williams')], default='alfa_romeo', max_length=250),
        ),
        migrations.AlterField(
            model_name='websiteuser',
            name='fave_team',
            field=models.CharField(choices=[('red_bull', 'Red Bull'), ('ferrari', 'Ferrari'), ('mercedes', 'Mercedes'), ('alpine', 'Alpine'), ('mclaren', 'McLaren'), ('alfa_romeo', 'Alfa Romeo'), ('aston_martin', 'Aston Martin'), ('haas', 'Haas'), ('alphatauri', 'AlphaTauri'), ('williams', 'Williams')], default='alfa_romeo', max_length=250),
        ),
    ]
